"""Adaptive planning schemas (docs/agent/AGENT_VISION.md §3, §3.1, §10).

Target design: docs/agent/PLANNER_OUTPUT_DESIGN.md. That document is the
authoritative source for *why* this module is shaped the way it is --
in particular §3 (what's in the Planner's output and what deliberately
isn't), §4 (LLM output vs. final Planner output are not the same object),
and §5 (the derived graph package).

Deliberately not a port of `services/agent/app/agent/planner/schemas.py` --
that shape is fixed-upfront (a full `subtasks` list decided in one pass) and
tied to the old fixed-workflow/capability-registry system. This module
supports the vision's adaptive rhythm instead: the Planner is invoked
repeatedly, each time producing only the next runnable chunk of steps, never
a full plan with placeholders for steps it doesn't yet have grounds to
decide.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from app.agent_core.reasoning_blocks.schemas import BaseReasoningBlockInput, BaseReasoningBlockOutput
from app.agent_core.request_understanding.schemas import RequestUnderstandingReasoningBlockOutput

RoleName = Literal[
    "retrieval",
    "interpretation",
    "calculation_validation",
    "simulation_planning",
    "composition",
]

PlanStatus = Literal["in_progress", "complete", "blocked_needs_clarification"]


class PlanStepDraft(BaseModel):
    """Raw LLM output for one step within a single invocation's batch
    (PLANNER_OUTPUT_DESIGN.md §4). `step_id` and any `depends_on` entries
    referring to a sibling in this same batch are simple local labels
    ("A", "B", ...) -- valid only within this one invocation, never a final
    identifier. A `depends_on` entry may also already be a real global id
    the model copied from what it was shown of the accumulated plan graph;
    the rewrite pass (`planning/rewrite.py`) is what tells the two apart.
    """

    step_id: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    success_criteria: list[str] = Field(default_factory=list)
    assumptions_to_verify: list[str] = Field(default_factory=list)


class PlanStep(BaseModel):
    """One unit of work the Orchestrator will dispatch to a subagent --
    final, validated form. Only ever constructed by the rewrite/validation
    pipeline in `planning/rewrite.py` from a batch of `PlanStepDraft`s, never
    parsed directly from raw LLM output. `step_id` is globally unique across
    the plan's whole lifetime; `depends_on` entries are fully resolved,
    either to a step in this same batch or to a step already in accumulated
    state (PLANNER_OUTPUT_DESIGN.md §4).

    No `role`, `risk_level`, or `title` field: role and reasoning-budget
    decisions belong to the Orchestrator, made fresh at dispatch time
    (§3/§7 of the vision doc), not fixed upfront by the Planner; `title` is
    redundant with `objective` and was cut for the same "two descriptions
    that could drift" reason `anticipated_followup` was folded into
    `plan_summary` below.
    """

    step_id: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    # What the Monitor checks this step's result against (see orchestrator.monitor).
    success_criteria: list[str] = Field(default_factory=list)
    assumptions_to_verify: list[str] = Field(default_factory=list)


class PlanGraph(BaseModel):
    """Derived by code from validated `PlanStep.depends_on` values -- never
    generated by the LLM (PLANNER_OUTPUT_DESIGN.md §5). Scoped to ONE
    invocation's own new steps (a delta), not the whole plan so far --
    `PlanExecutionState.plan_graph` (planning/state.py) is the single
    persistent accumulator that merges these deltas across invocations.

    `forward` is redundant with each step's own `depends_on`, collected here
    just for O(1) lookup. `dependents` is the reverse-edge view -- "what
    relies on this result" -- including edges pointing at steps outside this
    batch (already-completed steps from a prior invocation), which is
    exactly the piece of new information the accumulator needs to fold in.
    `execution_layers` falls out of the same topological/cycle-check pass
    already required for validation -- steps safe to dispatch concurrently.
    """

    forward: dict[str, list[str]] = Field(default_factory=dict)
    dependents: dict[str, list[str]] = Field(default_factory=dict)
    execution_layers: list[list[str]] = Field(default_factory=list)


class StateEntrySummary(BaseModel):
    """Compact index of one `StateEntry` -- what the Planner sees of prior
    results, never the full payload (keeps the Planner's own context bounded)."""

    entry_id: str
    step_id: str
    role: RoleName
    summary: str
    certainty_band: Literal["high", "medium", "low"]


class PlannerInvocationInput(BaseModel):
    """Everything one Planner invocation needs.

    `sub_asks`/`constraints`/`open_questions`/`implies_action_request` come
    from Request Understanding's own structured output (never lossily
    flattened into `user_goal` alone) -- additive fields, default
    empty/`False` for any caller that doesn't supply them.

    `plan_graph_so_far` is the whole-plan graph accumulated across every
    prior invocation (PLANNER_OUTPUT_DESIGN.md §5's "on the input side") --
    sourced from `PlanExecutionState.plan_graph`, never reconstructed from
    `state_index` prose each round.
    """

    user_goal: str
    original_user_message: str
    sub_asks: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    implies_action_request: bool = False
    confidence: float = Field(ge=0.0, le=1.0, default=0.7)
    state_index: list[StateEntrySummary] = Field(default_factory=list)
    plan_graph_so_far: PlanGraph = Field(default_factory=PlanGraph)
    monitor_flags: list[str] = Field(default_factory=list)
    replan_reason: str | None = None


def planner_input_from_understanding(
    understanding: RequestUnderstandingReasoningBlockOutput,
    *,
    original_user_message: str,
    state_index: list[StateEntrySummary] | None = None,
    plan_graph_so_far: PlanGraph | None = None,
    monitor_flags: list[str] | None = None,
    replan_reason: str | None = None,
) -> PlannerInvocationInput:
    """The one, explicit rendering of Request Understanding's output into the
    Planner's own input -- RU's output *is* the Planner's input by design, so
    this mapping deserves the same "one rendering, never duplicated"
    discipline as `_render_user_goal`, not something reconstructed ad hoc
    wherever it happens to be needed.

    The Planner should only ever be invoked when RU said `in_scope=True` --
    an internal call-order invariant, not a real system boundary, so a
    violation fails loudly here rather than silently producing an
    empty-objective Planner call.
    """
    assert understanding.in_scope, "planner_input_from_understanding called on an out-of-scope result"
    return PlannerInvocationInput(
        user_goal=understanding.user_goal or "",
        original_user_message=original_user_message,
        sub_asks=understanding.sub_asks,
        constraints=understanding.constraints,
        open_questions=understanding.open_questions,
        implies_action_request=understanding.implies_action_request,
        confidence=understanding.confidence,
        state_index=state_index or [],
        plan_graph_so_far=plan_graph_so_far or PlanGraph(),
        monitor_flags=monitor_flags or [],
        replan_reason=replan_reason,
    )


class PlannerReasoningBlockInput(BaseReasoningBlockInput):
    """The Planner's own reasoning-block input -- block mechanics
    (`block_id`, `output_schema`, ...) from the base, plus the Planner's
    actual domain input nested under one field. `task_context` stays at its
    inherited empty-dict default: the block reads typed fields off
    `planner_input` directly, never a dict."""

    planner_input: PlannerInvocationInput


class PlannerReasoningBlockOutput(BaseReasoningBlockOutput):
    """Raw LLM output for one invocation, before code post-processing
    (PLANNER_OUTPUT_DESIGN.md §4) -- `status`/`schema_valid`/`confidence`/
    `warnings`/`total_llm_calls_used` come from the base. Never the Planner's
    actual output -- `next_steps` here are `PlanStepDraft`s with unresolved
    local labels, and there is no `plan_graph` (that's computed by code
    afterward from the rewrite pipeline, see `PlannerInvocationOutput`)."""

    plan_status: PlanStatus
    plan_summary: str
    clarification_question: str | None = None
    next_steps: list[PlanStepDraft] = Field(default_factory=list)


class PlannerInvocationOutput(BaseModel):
    """What one Planner invocation returns -- the next chunk only, after
    code post-processing (PLANNER_OUTPUT_DESIGN.md §4).

    `plan_status` is explicit, never inferred from `next_steps` being empty
    (empty could mean "done" or "nothing to add this round due to a bug" --
    ambiguity this field removes entirely).

    `plan_graph` is always code-computed from the validated `next_steps`,
    never LLM output -- so it can never independently drift from the
    `depends_on` values it's derived from (§5).
    """

    plan_status: PlanStatus
    next_steps: list[PlanStep] = Field(default_factory=list)
    plan_summary: str
    clarification_question: str | None = None
    plan_graph: PlanGraph


__all__ = [
    "RoleName",
    "PlanStatus",
    "PlanStepDraft",
    "PlanStep",
    "PlanGraph",
    "StateEntrySummary",
    "PlannerInvocationInput",
    "planner_input_from_understanding",
    "PlannerReasoningBlockInput",
    "PlannerReasoningBlockOutput",
    "PlannerInvocationOutput",
]
